name: API Automation Tests

on:
  push:
    branches:
      - main

jobs:
  run-newman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Newman
        run: npm install -g newman newman-reporter-htmlextra

      - name: Run API Automation Collection
        run: |
         newman run "Project-07: API Automation with Postman + Newman/project07-automation.json" --reporters cli,htmlextra

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: newman-html-report
          path: newman/*.html
